[project]
name = "borealhdr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "albumentations>=1.4.18",
    "matplotlib>=3.7.5",
    "numpy>=1.24.4",
    "opencv-python>=4.11.0.86",
    "pandas>=2.0.3",
    "pillow>=10.4.0",
    "python-math>=0.0.1",
    "pyyaml>=6.0.3",
    "rasterio>=1.3.11",
    "scikit-image>=0.21.0",
    "scikit-learn>=1.3.2",
    "scipy>=1.10.1",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
    "tqdm>=4.67.1",
]
